name: bench

on: workflow_dispatch

jobs:
  benchee:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: bench

    strategy:
      matrix:
        elixir: ["1.16"]
        otp: ["26"]

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: bench-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            bench-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-
            bench-${{ matrix.otp }}-${{ matrix.elixir }}-refs/heads/master-

      - run: mix deps.get --only $MIX_ENV
      - run: mkdir results
      - run: mix run bench/build.exs | tee results/build.txt
      - run: mix run bench/xml.exs | tee results/xml.txt
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/*.txt
