name: mix

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    strategy:
      matrix:
        elixir: ["1.15", "1.16"]
        otp: ["25", "26"]

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: test-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            test-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-
            test-${{ matrix.otp }}-${{ matrix.elixir }}-refs/heads/master-

      - run: mix deps.get --only $MIX_ENV
      - run: mix compile --warnings-as-errors

      - run: docker run -d -p 9000:9000 minio/minio server /data
      - run: aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://testbucket
        env:
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_SECRET_ACCESS_KEY: minioadmin
          AWS_EC2_METADATA_DISABLED: true

      - run: mix test --include minio
        env:
          MINIO_REGION: us-east-1
          MINIO_ACCESS_KEY: minioadmin
          MINIO_SECRET_KEY: minioadmin
          MINIO_ENDPOINT_URL: http://127.0.0.1:9000

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16"
          otp-version: 26
      - run: mix format --check-formatted
